
dubbo:
  application:
    name: comsuer
    id: comsuer
    version: 1.0.0
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: dubbo-resis
    address: redis://127.0.0.1:6379
  scan:
    base-packages: coderLgx
server:
  port: 8080
spring:
  application:
    name: consumer